# Generated by Django 2.1.1 on 2018-12-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.ImageField(upload_to='photos/%y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
